server:
  port: 8501
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.12:3306/db_spzx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 192.168.5.12
      port: 6379
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml
